---

version: '3.8'

services:
    api:
        build:
            context: src
            args:
                - API_PORT=${API_PORT}
                - POETRY_VERSION=${POETRY_VERSION}
        container_name: ${PROJECT_NAME}_api
        restart: unless-stopped
        ports: 
            - '${MAPPING}:${API_PORT}'
        networks:
            - backend
        hostname: ${API_HOSTNAME}
        volumes:
            - $PWD/src:/code
        environment:
            - DB_HOST=${POSTGRES_HOSTNAME}
            - DB_USER=${POSTGRES_USER}
            - DB_NAME=${POSTGRES_DB}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_PORT=${POSTGRES_PORT}
            - PREFERRED_SLUG_LENGTH=${PREFERRED_SLUG_LENGTH}
            - SHORT_DOMAIN=${SHORT_DOMAIN}
        depends_on:
            - db
        command: bash -c "alembic upgrade head && uvicorn --host 0.0.0.0 --port ${API_PORT} --reload main:app"

    db:
        image: ${POSTGRES_IMAGE}
        container_name: ${PROJECT_NAME}_postgres
        restart: unless-stopped
        networks:
            - backend
        hostname: ${POSTGRES_HOSTNAME}
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}

networks:
    backend:
        name: ${PROJECT_NAME}_backend
        driver: bridge
