"""Create short_link table

Revision ID: 1ec00648a77b
Revises: 
Create Date: 2021-07-17 13:34:16.865746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec00648a77b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_link',
    sa.Column('slug', sa.String(length=12), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_link')
    # ### end Alembic commands ###
